# fly.toml app configuration file generated for salt on 2025-08-14T00:07:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'salt'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.24.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 1112
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
