name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build binary
        run: |
          go build -ldflags="-s -w" -o salt .
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: salt
          path: salt

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: salt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: salt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
